#!/usr/bin/env ansible-playbook
- name: Configure webserver with nginx
  hosts: webservers
  sudo: True
  tasks:
    - name: install nginx
      yum: name=nginx update_cache=yes
    
    - name: copy nginx config file
      copy: src=file/nginx.conf dest=/etc/nginx/nginx.conf

#    - name: enable configuration
#      file: >
#        dest=/etc/nginx/sites-enabled/default
#        src=/etc/nginx/sites-available/default
#        state=link

    - name: copy index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644

    - name: restart nginx
      service: name=nginx state=restarted
